// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRZ4-oJgniyksemCerTKWcwRl4jjLwiCw',
    appId: '1:506356825617:web:afb1e12e71f186b9643bb0',
    messagingSenderId: '506356825617',
    projectId: 'zerosbi1',
    authDomain: 'zerosbi1.firebaseapp.com',
    storageBucket: 'zerosbi1.firebasestorage.app',
    measurementId: 'G-RVQJMGQLHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEEQ_pAgH0QYPMZdQ3eze5OJYfjmt8X3k',
    appId: '1:506356825617:android:5320ca3f93204c51643bb0',
    messagingSenderId: '506356825617',
    projectId: 'zerosbi1',
    storageBucket: 'zerosbi1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcCvnn4ic3si8OdT2SJ_JpfHX7VLR6jLQ',
    appId: '1:506356825617:ios:79d2a7c60eeb1046643bb0',
    messagingSenderId: '506356825617',
    projectId: 'zerosbi1',
    storageBucket: 'zerosbi1.firebasestorage.app',
    iosClientId: '506356825617-550epehjubkip00ne1ti4lchr9095pq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.zerosbi1GradProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcCvnn4ic3si8OdT2SJ_JpfHX7VLR6jLQ',
    appId: '1:506356825617:ios:79d2a7c60eeb1046643bb0',
    messagingSenderId: '506356825617',
    projectId: 'zerosbi1',
    storageBucket: 'zerosbi1.firebasestorage.app',
    iosClientId: '506356825617-550epehjubkip00ne1ti4lchr9095pq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.zerosbi1GradProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRZ4-oJgniyksemCerTKWcwRl4jjLwiCw',
    appId: '1:506356825617:web:b2635efa3400c2cb643bb0',
    messagingSenderId: '506356825617',
    projectId: 'zerosbi1',
    authDomain: 'zerosbi1.firebaseapp.com',
    storageBucket: 'zerosbi1.firebasestorage.app',
    measurementId: 'G-95JJX5J19Y',
  );

}